org: jnrlouis
app: btc-frens-nft
service: btc-frens-nft
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  btcFrens:
    handler: handler.btcFrens
    events:
      - httpApi:
          path: /api/v1/btcFrens
          method: post

plugins:
  - serverless-plugin-typescript
  - serverless-offline
